
# ======================================================== #
# File automagically generated by GUI2Exe version 0.5.3
# Copyright: (c) 2007-2012 Andrea Gavana
# ======================================================== #

# Let's start with some default (for me) imports...

from distutils.core import setup
from py2exe.build_exe import py2exe

import glob
import os
import zlib
import shutil

# Remove the build folder
shutil.rmtree("build", ignore_errors=True)


class Target(object):
    """ A simple class that holds information on our executable file. """
    def __init__(self, **kw):
        """ Default class constructor. Update as you need. """
        self.__dict__.update(kw)
        

# Ok, let's explain why I am doing that.
# Often, data_files, excludes and dll_excludes (but also resources)
# can be very long list of things, and this will clutter too much
# the setup call at the end of this file. So, I put all the big lists
# here and I wrap them using the textwrap module.

data_files = [('GUI\AuiPanel', ['F:\\Ipcheck\\GUI\\AuiPanel\\__init__.pyc',
                                'F:\\Ipcheck\\GUI\\AuiPanel\\Rev.pyc',
                                'F:\\Ipcheck\\GUI\\AuiPanel\\Stat.pyc']),
              ('GUI\Report', ['F:\\Ipcheck\\GUI\\Report\\__init__.pyc',
                              'F:\\Ipcheck\\GUI\\Report\\buyit.pyc',
                              'F:\\Ipcheck\\GUI\\Report\\Pnl0.pyc',
                              'F:\\Ipcheck\\GUI\\Report\\r3.pyc',
                              'F:\\Ipcheck\\GUI\\Report\\report3.pyc']),
              ('Logs', ['F:\\Ipcheck\\Logs\\about.txt',
                        'F:\\Ipcheck\\Logs\\disit.txt']),
              ('Database', ['F:\\Ipcheck\\Database\\__init__.pyc',
                            'F:\\Ipcheck\\Database\\Menu.db',
                            'F:\\Ipcheck\\Database\\wxsq.pyc']),
              ('GUI', ['F:\\Ipcheck\\GUI\\__init__.pyc',
                       'F:\\Ipcheck\\GUI\\BG.pyc',
                       'F:\\Ipcheck\\GUI\\MainMenu.pyc',
                       'F:\\Ipcheck\\GUI\\proman.pyc',
                       'F:\\Ipcheck\\GUI\\window.pyc']),
              ('GUI\Input', ['F:\\Ipcheck\\GUI\\Input\\__init__.pyc',
                             'F:\\Ipcheck\\GUI\\Input\\buyit.pyc',
                             'F:\\Ipcheck\\GUI\\Input\\Pnl0.pyc']),
              ('GUI\Program', ['F:\\Ipcheck\\GUI\\Program\\__init__.pyc',
                               'F:\\Ipcheck\\GUI\\Program\\buyit.pyc',
                               'F:\\Ipcheck\\GUI\\Program\\Pnl0.pyc',
                               'F:\\Ipcheck\\GUI\\Program\\quit.pyc']),
              ('GUI\Help', ['F:\\Ipcheck\\GUI\\Help\\__init__.pyc',
                            'F:\\Ipcheck\\GUI\\Help\\about.pyc',
                            'F:\\Ipcheck\\GUI\\Help\\Pnl0.pyc']),
              ('Config', ['F:\\Ipcheck\\Config\\__init__.pyc',
                          'F:\\Ipcheck\\Config\\Init.pyc',
                          'F:\\Ipcheck\\Config\\program.ini']),
              ('Utility', ['F:\\Ipcheck\\Utility\\__init__.pyc',
                           'F:\\Ipcheck\\Utility\\clacal2.pyc',
                           'F:\\Ipcheck\\Utility\\clacal3.pyc'])]

includes = ['wx', 'khayyam']
excludes = ['_gtkagg', '_tkagg', 'bsddb', 'curses', 'email', 'pywin.debugger',
            'pywin.debugger.dbgcon', 'pywin.dialogs', 'tcl',
            'Tkconstants', 'Tkinter']
packages = ['GUI', 'Database', 'Utility']
dll_excludes = ['libgdk-win32-2.0-0.dll', 'libgobject-2.0-0.dll', 'tcl84.dll',
                'tk84.dll']
icon_resources = []
bitmap_resources = []
other_resources = [(1, 24, 'F:\\Ipcheck\\Res\\Pics\\__init__.py'), (2, 24,
                   'F:\\Ipcheck\\Res\\Pics\\Mypic1.jpg'), (3,
                   24, 'F:\\Ipcheck\\Res\\Pics\\Mypic2.jpg'),
                   (4, 24, 'F:\\Ipcheck\\Res\\Pics\\Mypic3.jpg'),
                   (5, 24, 'F:\\Ipcheck\\Res\\Pics\\Mypic4.jpg'),
                   (6, 24, 'F:\\Ipcheck\\Res\\Pics\\Mypic5.jpg'),
                   (7, 24, 'F:\\Ipcheck\\Res\\Pics\\Mypic6.jpg')]


# This is a place where the user custom code may go. You can do almost
# whatever you want, even modify the data_files, includes and friends
# here as long as they have the same variable name that the setup call
# below is expecting.

# No custom code added


# Ok, now we are going to build our target class.
# I chose this building strategy as it works perfectly for me :-D

GUI2Exe_Target_1 = Target(
    # what to build
    script = "mainpro.py",
    icon_resources = icon_resources,
    bitmap_resources = bitmap_resources,
    other_resources = other_resources,
    dest_base = "mainpro",    
    version = "0.1",
    company_name = "No Company",
    copyright = "No Copyrights",
    name = "Py2Exe Sample File",
    
    )

# No custom class for UPX compression or Inno Setup script

# That's serious now: we have all (or almost all) the options py2exe
# supports. I put them all even if some of them are usually defaulted
# and not used. Some of them I didn't even know about.
                    
setup(

    # No UPX or Inno Setup

    data_files = data_files,

    options = {"py2exe": {"compressed": 0, 
                          "optimize": 0,
                          "includes": includes,
                          "excludes": excludes,
                          "packages": packages,
                          "dll_excludes": dll_excludes,
                          "bundle_files": 3,
                          "dist_dir": "dist",
                          "xref": False,
                          "skip_archive": False,
                          "ascii": False,
                          "custom_boot_script": '',
                         }
              },

    zipfile = None,
    console = [],
    windows = [GUI2Exe_Target_1],
    service = [],
    com_server = [],
    ctypes_com_server = []
    )

# This is a place where any post-compile code may go.
# You can add as much code as you want, which can be used, for example,
# to clean up your folders or to do some particular post-compilation
# actions.

# No post-compilation code added


# And we are done. That's a setup script :-D

